@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

skinparam SequenceMessageAligment center
skinparam Style strictuml
skinparam actorStyle awesome

actor Користувач as user

==Додавання міста==
user -> "Web-застосунок": Додати місто
"Web-застосунок" -> "Сервер застосунку": Перевірка на наявність
alt Міста нема у базі
    "Сервер застосунку" -> API: Запит
    API -> "Сервер застосунку": Відповідь
    "Сервер застосунку" -> "Web-застосунок": Додає місто

else Місто вже є в базі
    "Сервер застосунку" -> "Web-застосунок"

end
==Видалення міста==
user -> "Web-застосунок": Видалити місто
"Web-застосунок" -> "Сервер застосунку": Виклик метода
"Сервер застосунку" -> "Web-застосунок": Видалення міста
@enduml